<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <NoWarn>$(NoWarn);S1066</NoWarn>
    <NoWarn>$(NoWarn);S112</NoWarn>
  </PropertyGroup>

  
  <ItemGroup>
    <PackageReference Include="Hangfire" Version="1.8.14" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.14" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="6.0.0" />
    <PackageReference Include="NCrontab.Signed" Version="3.3.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Tewelde.FuncScript" Version="0.2.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\orch.common\orch.common.csproj" />
  </ItemGroup>

</Project>
