<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
	  <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<NoWarn>1701;1702;1591</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<NoWarn>1701;1702;1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
    <ProjectReference Include="..\..\function-script\funcscript\funcscript.csproj" />
    <ProjectReference Include="..\orch.common\orch.common.csproj" />
    <ProjectReference Include="..\orch.core\orch.core.csproj" />
    <ProjectReference Include="..\orch.utils.web\orch.utils.web.csproj" />
  </ItemGroup>

</Project>
