// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using orch.content;

#nullable disable

namespace orch.content.Migrations
{
    [DbContext(typeof(ContentDb))]
    [Migration("20221005044930_content_ref")]
    partial class content_ref
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("orch.content.model.ContentFile", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("MimeType")
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<int>("RefCount")
                        .HasColumnType("integer")
                        .HasColumnName("ref_count");

                    b.HasKey("FileId");

                    b.ToTable("content_file");
                });

            modelBuilder.Entity("orch.content.model.ContentReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid")
                        .HasColumnName("file_id");

                    b.Property<int>("RefCount")
                        .HasColumnType("integer")
                        .HasColumnName("ref_count");

                    b.Property<string>("RefText")
                        .HasColumnType("text")
                        .HasColumnName("ref_text");

                    b.HasKey("Id");

                    b.ToTable("content_reference");
                });
#pragma warning restore 612, 618
        }
    }
}
